# **numpy를 이용한 행렬 연산**

- 행렬 생성



In [5]:
import numpy as np

In [6]:
a = np.array([[1, 2], [3, 4]])

In [7]:
# 전치 행령(행과 열을 바꿈)

a = np.array([[1,2,3], [4,5,6]])
print(a.T) # 전체 행렬 출력
 

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# 행렬 차원 확인
a = np.array([[1,2,3],[4,5,6]])
print(a.shape) # 2행 3열

(2, 3)


In [12]:
# 행렬 형태 변경
a = np.array([[1,2,3],[4,5,6]])
b = np.reshape(a, (3,2)) # 

print(b.shape)
print(b)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [15]:
# 배열간 사칙연산
# 행렬의 형태가 다른경우에는 불가

a = np.array([[1,2,3], [4,5,6]])
b = np.array([[2,3,4], [5,6,7]])

print(a+b)
print(a+3)

[[ 3  5  7]
 [ 9 11 13]]
[[4 5 6]
 [7 8 9]]


In [16]:
print(a-b)
print(a-2)

[[-1 -1 -1]
 [-1 -1 -1]]
[[-1  0  1]
 [ 2  3  4]]


In [17]:
print(a * b)
print(a * 2)

[[ 2  6 12]
 [20 30 42]]
[[ 2  4  6]
 [ 8 10 12]]


In [18]:
print(a/b)
print(a/2)

[[0.5        0.66666667 0.75      ]
 [0.8        0.83333333 0.85714286]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]]


In [19]:
# 행렬의 곱셈(cnn, 이미지처리시 자주 사용)
a = np.array([1,2,3])
b = np.array([4,5,6])

print(np.dot(a,b)) 

32


In [20]:
a = np.array([[1,2,3], 
              [4,5,6]])
b = np.array([[1,2],
              [3,4],
              [5,6]])

print(np.dot(a,b))

[[22 28]
 [49 64]]
